name: SSH Command Execution

on:
  push:
    branches:
      - main

jobs:
  execute_ssh_command:
    runs-on: ubuntu-latest

    steps:
      - name: Get Hostname
        id: get_hostname
        run: echo "::set-env name=SERVER_NAME::$(hostname)"
      
      - name: Get OS Info
        run: uname -a
      - name: Get CPU Info
        run: cat /proc/cpuinfo
      - name: Get Memory Info
        run: free -h
      - name: Get Storage Info
        run: df -h

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Configure SSH
        run: |
          echo -e "Host ${{ steps.get_hostname.outputs.SERVER_NAME }}\n\tHostName ${{ github.runner.ip }}\n\tUser user\n\tIdentityFile ~/.ssh/id_rsa\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Run SSH command
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh ${{ steps.get_hostname.outputs.SERVER_NAME }} "ls -la"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
