name: SSH Command Execution

on:
  push:
    branches:
      - main

jobs:
  execute_ssh_command:
    runs-on: ubuntu-latest

    steps:
      - name: Get Hostname and IP
        id: hostname_ip
        run: |
          echo "::set-output name=hostname::$(hostname)"
          echo "::set-output name=ip_address::$(hostname -I | cut -d' ' -f1)"

      - name: Save Hostname and IP
        run: |
          echo "HOSTNAME=$(echo '${{ steps.hostname_ip.outputs.hostname }}')" >> $GITHUB_ENV
          echo "IP_ADDRESS=$(echo '${{ steps.hostname_ip.outputs.ip_address }}')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Generate SSH key
        run: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""

      - name: Copy public key to authorized_keys
        run: cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

      - name: Print public key
        run: cat ~/.ssh/id_rsa.pub
        id: print_public_key

      - name: Configure SSH
        run: |
          echo -e "Host ${{ env.HOSTNAME }}\n\tHostName ${{ env.IP_ADDRESS }}\n\tUser user\n\tIdentityFile ~/.ssh/id_rsa\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Set permissions for SSH key
        run: chmod 600 ~/.ssh/id_rsa

      - name: Run SSH command
        run: |
          ssh ${{ env.HOSTNAME }} "ls -la"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
