name: SSH Command Execution

on:
  push:
    branches:
      - main

jobs:
  execute_ssh_command:
    runs-on: ubuntu-latest

    steps:
      - name: Get Hostname
        run: hostname
      
      - name: Get OS Info
        run: uname -a
      - name: Get CPU Info
        run: cat /proc/cpuinfo
      - name: Get Memory Info
        run: free -h
      - name: Get Storage Info
        run: df -h

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Get public IP
        id: get_ip
        run: echo "::set-output name=ip_address::$(curl -s ifconfig.me)"

      - name: Configure SSH
        run: |
          echo -e "Host $SERVER_NAME\n\tHostName ${{ steps.get_ip.outputs.ip_address }}\n\tUser user\n\tIdentityFile ~/.ssh/id_rsa\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Run SSH command
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh $SERVER_NAME "ls -la"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_NAME: ${{ env.SERVER_NAME }}
